apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vrspace-tls
  namespace: default
spec:
  secretName: vrspace-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: vrserver.endpoints.metaverse-363005.cloud.goog
  dnsNames:
  - vrserver.endpoints.metaverse-363005.cloud.goog