# This is a workflow to build, deploy and test A-Frame applications.
name: Solipsisworld Deployment Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  Name : vrserver
  Project_Name : metaverse-363005
  Cluster_name : vrspace-cluster
  Server_Name : vrspace
  Service_Name : vrspace-service
  URL: "/content/worlds/solipsisworld/movements.html" 

jobs:
  build_deploy_test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install SSH Key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.RSA_KEY }} 
            known_hosts: 'placeholder'
        
        - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
        - name: Setting up
          uses: google-github-actions/setup-gcloud@v0
          with:
            version: '286.0.0'
            service_account_key: ${{ secrets.GCP_KEY }}
            service_account_email: ${{ secrets.SERVICE_EMAIL }}
            project_id:  ${{ env.Project_Name }}
            
        - name: Auth Docker
          run: |-
            gcloud auth configure-docker -q
            
        - name: Build Docker Image
          run: |-
            docker build -t ${{ env.Name }} .
            
        - name: Tag Docker Image
          run: |-
            docker tag ${{ env.Name }} gcr.io/${{ env.Project_Name }}/${{ env.Name }}
            
        - name: Push Docker Image
          run: |-
            docker push gcr.io/${{ env.Project_Name }}/${{ env.Name }}

        - name: Deploy Docker Image
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }} 
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.RSA_KEY }} 
            port: 22
            script: | 
              gcloud container clusters create ${{ env.Cluster_name }} 2> /dev/null
              gcloud container clusters get-credentials ${{ env.Cluster_name }} 
              kubectl delete deployment ${{ env.Server_Name }}
              kubectl delete service ${{ env.Service_Name }} 
              sleep 10
              kubectl create deployment ${{ env.Server_Name }} --image=gcr.io/${{ env.Project_Name }}/${{ env.Name }}
              kubectl expose deployment ${{ env.Server_Name }} --name=${{ env.Service_Name }} --type=LoadBalancer --port=80 --target-port=8080
              sleep 60
              kubectl get services ${{ env.Service_Name }} | awk '{ print $4 }' | tail -1 > temp.txt
              echo -n ${{ env.URL }} >> temp.txt
              /home/metaverseops/testproject/code/webapp_test.py temp.txt