name: PULL

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - unit-test
      - lint-test

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci
      
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
            echo "display error" > report.txt;
            for changed_file in ${{ steps.files.outputs.all }}; 
            do
            if [[ $changed_file == *.js ]]
            then
              echo $changed_file >> report.txt
              npx eslint $changed_file >> report.txt || true

            fi
            done

      - name: Read Report
        id: report
        uses: juliangruber/read-file-action@v1
        with:
        path: ./report.txt

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: smtp://${{secrets.email_sender}}:${{secrets.email_password}}@smtp-mail.outlook.com:587
          # Required mail server address if not connection_url:
          server_address: smtp-mail.outlook.com
          # Server port, default 25:
          server_port: 587
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          subject: Github Actions job result
          # Required recipients' addresses:
          to:  elina.ding@outlook.com
          # Required sender full name (address can be skipped):
          from: Metaverse CICD Developer # <user@example.com>
          # Optional plain body:
          body:  ${{ steps.report.outputs.content }}
          ignore_cert: true

      # - name: Create Pull Request
      #   id: cpr
      #   uses: peter-evans/create-pull-request@v4
      #   with:
      #     token: ${{ secrets.PAT }}
      #     commit-message: Update report
      #     committer: GitHub <noreply@github.com>
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     signoff: false
      #     branch: example-patches
      #     delete-branch: true
      #     title: '[Example] Update report'
      #     body: |
      #       Update report
      #       - Updated with *today's* date
      #       - Auto-generated by [create-pull-request][1]

      #       [1]: https://github.com/peter-evans/create-pull-request
      #     labels: |
      #       report
      #       automated pr
